### ISSUE TITLE
Implement Checkout on Order#Show

### ISSUE THREAD

**Issue by limichelle21** [limichelle21/ecommerce#21]
@mjthompsgb - Where would a "Checkout" link on the Order#Show view direct to? Would want to direct to a view that includes: 
- total price 
- customer information input/update fields (name, address, phone, email) depending on whether or not current_user has already signed in
- Place to include credit card information (assuming this is related to Stripe integration) 

I searched for Stripe/Rails integration and found the following resource on Stripe - (https://stripe.com/docs/checkout/rails). Will it be sufficient to follow their integration (including controllers and views) for my Checkout page?

**Comment by limichelle21** [comment]
References:

http://stillriversoftware.com/blog/integrating-stripe-into-your-ruby-on-rails-app/

https://stripe.com/docs/checkout/rails

**Comment by mjthompsgb** [comment]
The first comment what you had mentioned to include sounds right. Showing what the price will be and probably include shipping options and/or costs.

Do you want to use the simple Stripe payment button or have the form right on your page? Having the form right on your page requires a little more work and some Javascript to send off the info to Stripe and get a token back for the credit card to use on the backend to make the payment happen.

The `stillriversoftware.com` implementation looks decent and has both options.

**Comment by limichelle21** [comment]
- [x] Installed Stripe, Charges controller/views, configured Stripe, basic Checkout page
- [x]  Edit Charges#New view to display the charge amount from current_order.subtotal (need @current_order?) and change script's data-amount to the same value
- [x] Charges#create -- set @amount to equal current_order.subtotal
- [x] Charges#create -- clear cart after charge has been created. Can I call a method from the cart controller? Where should the method be located? A user may want to clear their cart in addition to deleting an individual item - in that case, could I call a "clear_cart" method in the Charges controller from the cart controller?

**Comment by limichelle21** [comment]
@mjthompsgb I'd want to have the form right on my page. Been trying to wrap my head around implementation of a custom form:
- I went through a jQuery course on codeacademy, but it's quite fuzzy. Where would I put the jQuery code (example from `stillriver`)? Directly on my page (charges/new.html.erb) or elsewhere?
- What is coffeescript, and how does it relate to rails? I see my JS directory has a bunch of files with `.coffee` extensions

```
 <%= form_tag charges_path, id: 'stripeForm' do -%>
   <script src="https://checkout.stripe.com/checkout.js"></script>
   <article>
     <%= label_tag 'amount', 'To Pay', class: 'amount' %>
     <%= label_tag 'amount', "$#{@amount}.00", class: "amount-figure" %>
   </article> <br>
   <button id="stripe-button">&nbsp;</button>
   <%= hidden_field_tag 'stripeToken' %>
   <%= hidden_field_tag 'stripeEmail' %>
   <%= hidden_field_tag 'stripeAmount' %>

   <script>
     var handler = StripeCheckout.configure({
       key: "<%= Settings[Rails.env]['stripe']['publishable_key'] %>",
       token: function (token, args) {
         $("#stripeToken").value = token.id;
         $("#stripeEmail").value = token.email;
         $("#stripeAmount").value = <%= @amount %>;
         $("#stripeForm").submit();
       }
     });

     $('#stripe-button').on('click', function (e) {
       // Open Checkout with further options
       handler.open({
         name: 'Your customer name',
         description: 'Your description goes here',
         amount: <%= @amount * 100 %>
       });
     e.preventDefault();
     });

     $(window).on('popstate', function() {
       handler.close();
     });
   </script>
 <% end %>
```

**Comment by mjthompsgb** [comment]
Hi Michelle,

If you haven't got the stripe form working yet we can get that going tonight.

Coffeescript is a way to right Javascript but it feels more like Ruby. You write the coffeescript and it compiles down to vanilla JS. I've used it a little and definitely want to use it more because it is very awesome. Rails comes with a Gem that will compile it on the fly which is super helpful. There are also ways to compile it without Rails if you wanted to right a JS only app.
