### ISSUE TITLE
Create the Order Views

### ISSUE THREAD

**Issue by limichelle21** [limichelle21/ecommerce#9]
Order Show view for Customer
- contains a table for products, each row is an Order Line
- Also include base customer information (name, address, phone number, email)
- Update button --- update quantities of product (link to update Order Line?)
- Delete button --- removes an Order Line (product)

Order Show view for Owner
- IF order is completed, view should reflect date paid, amount paid

Order Index view for Customer
- list of all orders for the current_user
- Order number == a link to the Customer's Order show view
- show "completed" status - a checkbox checked for yes, unchecked for no 

Order Index view for Owner
- a list of all orders for all customers
- each Order should have an Order number, Customer Name, and completed status (checkbox)

**Comment by limichelle21** [comment]
Updated nested routes - nesting OrderLines under Orders since all OrderLines must be accessed through an Order

**Comment by limichelle21** [comment]
Customer Order#Show view PENDING:
- Delete Item button
- Update Quantity button route
- an Order price total (sum of order_line.total_price) 
- Move quantity + field to be one line

**Comment by limichelle21** [comment]
Completed:
- Delete Item button
- Update quantity button

Issue:
- No route matches [POST] "/12/orders/9" (/store_id/orders/order_id)

**Comment by limichelle21** [comment]
Completed:
- Order price total (sum of all order_line.total_price)

**Comment by limichelle21** [comment]
Issue:
http://localhost:3000/12/orders/21
- When attempting to Delete Item from Order#Show, get a No Route error: _No route matches [POST] "/12/orders/21"_ (/store_id/orders/order_id) ---> think it's looking for a Order#update or Order#create action?
- @mjthompsgb : How can I point the Update/Delete buttons towards the Order Line controller? 

```
<%= form_for (:order_line) do |f| %> 
    <div class="row"> 
        <div class="col-xs-4"> 
            <%= f.number_field :quantity, value: order_line.quantity, class: "form-control", min: 1, maxlength: 2 %> 
            <%= f.hidden_field :product_id, value: order_line.product.id %> 
        </div> 
        <div class="col-xs-8 text-right"> 
            <div class="btn-group"> 
                <%= f.submit "Update Quantity", method: :patch, class: "btn btn-success" %>         
                <%= f.submit "Remove Item", method: :delete, class: "btn btn-danger", data: {confirm: 'Are you sure you want to remove item from your cart?'} %> 
                <br> 
                <br> 
                <h4><b>Total Price: $<%= order_line.total_price %></b></h4> 
            </div> 
        </div> 
    </div> 
<% end %>
```

**Comment by mjthompsgb** [comment]
Yes it looks like its routing to the Order#Create action right now.

You would have to make a custom route or use the correct route helper in the `form_for` to make it go to the correct controller and action. Form for typically takes an object so if each row is a `form_for` you could probably replace `(:order_line)` with `order_line` which would be an instance of order_line as you loop through all of the order_lines.

**Comment by limichelle21** [comment]
Resolved 7/28/16

`_cart_row.html.erb` - routing to `:order_line` with `method: :patch` and `method: :delete`

```
<%= form_for :order_line, url: store_order_line_path(current_store.id, order_line.id), method: :patch, remote: true do |f| %>

                    <h4 class="text-right">Unit Price: $<%= order_line.product.price_in_cents %></h4>
                    <div class="row">
                        <div class="col-xs-4">
                            <%= f.number_field :quantity, value: order_line.quantity, class: "form-control", min: 1 %>
                            <%= f.hidden_field :product_id, value: product.id %>
                        </div>
                        <div class="col-xs-8 text-right">
                            <div class="btn-group">
                                <%= f.submit "Update Quantity", class: "btn btn-success" %>     
                                <%= link_to "Delete", store_order_line_path(current_store.id, order_line.id), method: :delete, data: {confirm: "Are you sure you want to delete the product '#{order_line.product.title}'from your cart?"}, class: "btn btn-danger", remote: true %>    
                            </div>
                        </div>
                    </div>

                    <h4 class="subtotal">Subtotal: $<%= order_line.total_price %></h4>
                <% end %>
```
